[install.filesystem.root]
type = "xfs"

# We add the ignition.firstboot and ignition.platform.id for testing purpose
# as b-i-b does not support yet adding ignition osbuild stage to the generated manifest
# remove those kargs once supported.
[install]
kargs = ["rw", "console=tty0", "console=ttyS0", "ignition.firstboot", "ignition.platform.id=qemu"]
#root-mount-spec = "LABEL=root"

# Uncomment once the bootc binary including the new ostree option landed in FCOS
#[install.ostree]
#bls-append-except-default = 'grub_users=""'
